# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 130c0b704083521dcadebb518abfb85de80497784262c10b777ea5e46d3944cc6917f4ab94dcf15e39ba794f17c58ed44054d5a3f5f390acf4a3f63601cebe39

test:
  secret_key_base: 071e4f311a399ed03a383fb5d9508c8bb517076fbc68d11315bc3832a6b1c261d1f268944ce1b41acd48297f45a1dd18afb0706646e013bf02beafefbd5a38da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
